---
name: tasmota-addon
slug: tasmota-addon-test
version: 1.1
description: Just a Simple Addon
url: https://github.com/jewestyes
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  ssh_ip: ""
  ssh_username: ""
  ssh_password: ""
  ssh_command: []
  device_ip: []
  mqtt_broker: ""
  wifi_ssid: ""
  wifi_pass: ""
  send_with: MQTT
schema:
  ssh_ip: match(^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}$)
  ssh_username: str
  ssh_password: password
  ssh_command:
    - str?
  device_ip:
    - str?
  mqtt_broker: str?
  wifi_ssid: match(^(?=.{2,30}$)[a-zA-Z0-9._]+$)
  wifi_pass: match(^(?=.{8,30}$)[a-zA-Z0-9._]+$)
  send_with: list(MQTT|HTTP)